services:
  postgres:
    image: postgres:15-alpine
    environment:
      POSTGRES_DB: finance_tracker
      POSTGRES_USER: tat_admin
      POSTGRES_PASSWORD: tat_admin_26
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U tat_admin -d finance_tracker"]
      interval: 30s
      timeout: 5s
      retries: 3

volumes:
  postgres_data:
